<?php

return [
    'idSite:int|string|int[]' => [
        1,
        2,
    ],
    'period:\'day\'|\'week\'|\'month\'|\'year\'|\'range\'' => 'day',
    'period:"day"|"week"|"month"|"year"|"range"' => 'day',
    'date:string' => '2026-05-01',
    'segment:string' => 'countryCode==NZ',
    'columns:list<string>|string' => 'example_columns',
    'idSites:int[]|int|string' => 1,
    '_hideImplementationData:bool' => true,
    '_showAllSegments:bool' => true,
    'idSite:int|string' => 1,
    'apiModule:string' => 'example_apiModule',
    'apiAction:string' => 'example_apiAction',
    'apiParameters:array<string,mixed>' => [
        'example',
    ],
    'language:string|false' => 'example_language',
    'period:string|false' => 'day',
    'date:string|false' => '2026-05-01',
    'hideMetricsDoc:bool' => true,
    'showSubtableReports:bool' => true,
    'idSite:int|string|false' => 1,
    'period:string' => 'day',
    'segment:string|false' => 'countryCode==NZ',
    'apiParameters:array<string,mixed>|false' => [
        'example',
    ],
    'idGoal:int|string|false' => 1,
    'showTimer:bool' => true,
    'idSubtable:int|string|false' => 1,
    'showRawMetrics:bool' => true,
    'format_metrics:string|null' => 'nb_conversions',
    'idDimension:int|string|false' => 1,
    'columns:string[]|string|false' => 'example_columns',
    'label:string|false' => 'example_label',
    'column:string|false' => 'example_column',
    'legendAppendMetric:bool|string' => true,
    'labelUseAbsoluteUrl:bool|string' => true,
    'labelSeries:string|false' => 'example_labelSeries',
    'showGoalMetricsForGoal:int|string|false' => 10,
    'urls:string[]' => [
        'example',
    ],
    'pluginName:string' => 'Example name',
    'segmentName:string' => 'Example name',
    'idSite:int' => 1,
    'idExperiment:int' => 1,
    'segment:string|null|false' => 'countryCode==NZ',
    'successMetric:string' => 'nb_conversions',
    'name:string' => 'Example name',
    'hypothesis:string' => 'Changing the CTA increases conversions',
    'description:string' => 'Example description',
    'variations:array<int,array<string,mixed>>' => [
        [
            'name' => 'Original',
            'percentage' => 50,
        ],
        [
            'name' => 'Variation 1',
            'percentage' => 50,
            'redirect_url' => 'https://example.com/variation',
        ],
    ],
    'includedTargets:array<int,array<string,mixed>>' => [
        [
            'attribute' => 'path',
            'type' => 'equals',
            'value' => '/pricing',
        ],
    ],
    'successMetrics:array<int,array<string,mixed>>' => [
        [
            'metric' => 'nb_conversions',
        ],
    ],
    'confidenceThreshold:int|float|string' => 95.0,
    'mdeRelative:int' => 10,
    'percentageParticipants:int' => 100,
    'excludedTargets:array<int,array<string,mixed>>' => [
        [
            'attribute' => 'path',
            'type' => 'equals',
            'value' => '/pricing',
        ],
    ],
    'startDate:string|false' => '2026-05-01 00:00:00',
    'endDate:string|false' => '2026-05-01 00:00:00',
    'forwardUtmParams:bool' => true,
    'forwardAllQueryParams:bool' => true,
    'statuses:string|array<int,string>' => [
        'running',
        'finished',
    ],
    'columns:list<string>|string|false' => 'example_columns',
    'expanded:bool' => true,
    'idSubtable:int|null|false' => 1,
    'depth:int|null|false' => 10,
    'flat:bool' => true,
    'pageUrl:string' => 'https://example.com/',
    'pageName:string' => 'Example name',
    'downloadUrl:string' => 'https://example.com/',
    'outlinkUrl:string' => 'https://example.com/',
    'offset:int|string' => 0,
    'limit:int|string' => 100,
    'filterByUserLogin:string|null' => 'example_filterByUserLogin',
    'filterByActivityType:string|null' => 'example_filterByActivityType',
    'period:\'day\'|\'week\'|\'month\'|\'year\'|\'range\'|null' => 'day',
    'period:"day"|"week"|"month"|"year"|"range"|null' => 'day',
    'date:string|null' => '2026-05-01',
    'filterLimit:int|string' => 100,
    'idSite:int|null' => 1,
    'idExport:int' => 1,
    'type:string' => 'example_type',
    'parameters:array' => [
        'example',
    ],
    'note:string' => 'example_note',
    'starred:bool' => true,
    'idNote:int' => 1,
    'note:string|null' => 'example_note',
    'starred:bool|null' => true,
    'idSite:string' => 'example_idSite',
    'lastN:int|null' => 10,
    'getAnnotationText:bool' => true,
    'columns:string|array|false' => [
        'example',
    ],
    'columns:string|string[]|null' => 'example_columns',
    'secondaryDimension:\'pages\'|\'documents\'|null' => 'pages',
    'secondaryDimension:"pages"|"documents"|null' => 'pages',
    'idSubtable:int' => 1,
    'displayDateRange:string' => '2026-05-01',
    'cohorts:string' => 'example_cohorts',
    'filter_limit:int|false' => 100,
    'metric:string|null' => 'nb_conversions',
    'formatMetics:string|int' => 10,
    'idFailure:int|string' => 1,
    'idLogCrashes:int[]|int|string' => 1,
    'idLogCrash:int' => 1,
    'ignore:bool|int' => true,
    'filter_limit:int' => 100,
    'filter_offset:int' => 0,
    'fetchRecentActions:bool|int' => true,
    'filter_sort_column:string' => 'example_filter_sort_column',
    'filter_sort_order:string' => 'example_filter_sort_order',
    'columns:array<int,string>|string|false' => [
        'example',
    ],
    'filter_pattern:string' => 'example_filter_pattern',
    'expanded:bool|int' => true,
    'flat:bool|int' => true,
    'lastMinutes:int' => 10,
    'idAlert:int' => 1,
    'subPeriodN:int|string' => 10,
    'idSites:string|array' => [
        1,
        2,
    ],
    'ifSuperUserReturnAllAlerts:bool' => true,
    'period:\'day\'|\'week\'|\'month\'' => 'day',
    'period:"day"|"week"|"month"' => 'day',
    'emailMe:bool' => true,
    'additionalEmails:list<string>' => 'user@example.com',
    'phoneNumbers:list<string>' => 'example_phoneNumbers',
    'metric:string' => 'nb_conversions',
    'metricCondition:string' => 'nb_conversions',
    'metricValue:float|int|string' => 1.5,
    'comparedTo:int' => 10,
    'reportUniqueId:string' => 'example_reportUniqueId',
    'reportCondition:false|string' => 'example_reportCondition',
    'reportValue:false|string' => 'example_reportValue',
    'reportMediums:list<\'email\'|\'mobile\'|\'slack\'|\'teams\'>' => 'email',
    'reportMediums:list<"email"|"mobile"|"slack"|"teams">' => 'email',
    'slackChannelID:string' => 'example_slackChannelID',
    'msTeamsWebhookUrl:string' => 'https://example.com/',
    'idDimension:int' => 1,
    'idSubtable:int|false' => 1,
    'scope:\'visit\'|\'action\'' => 'visit',
    'scope:"visit"|"action"' => 'visit',
    'active:bool|int' => true,
    'extractions:array<int,array{dimension:string,pattern:string}>' => [
        'example',
    ],
    'caseSensitive:bool|int' => true,
    'caseSensitive:bool|int|null' => true,
    'idCustomReport:int' => 1,
    'idDestinationSites:int[]' => [
        'example',
    ],
    'reportType:string' => 'example_reportType',
    'metricIds:string[]' => [
        'nb_conversions',
    ],
    'categoryId:string|false' => 'example_categoryId',
    'dimensionIds:string[]' => [
        'example',
    ],
    'subcategoryId:string|false' => 'example_subcategoryId',
    'segmentFilter:string' => 'example_segmentFilter',
    'multipleIdSites:int[]|string[]' => [
        'example',
    ],
    'subCategoryReportIds:int[]' => [
        'example',
    ],
    'skipCategoryMetadata:bool' => true,
    'columns:string|false' => 'example_columns',
    'segment:string|false|null' => 'countryCode==NZ',
    '_leavePiwikCoreVariables:bool' => true,
    '_leavePriceViewedColumn:bool' => true,
    'login:string' => 'example_login',
    'returnDefaultIfEmpty:bool' => true,
    'dashboardName:string' => 'Example name',
    'addDefaultWidgets:bool' => true,
    'idDashboard:int' => 1,
    'copyToUser:string' => 'example_copyToUser',
    'secondaryDimension:\'eventAction\'|\'eventName\'|false' => 'eventAction',
    'secondaryDimension:"eventAction"|"eventName"|false' => 'eventAction',
    'secondaryDimension:\'eventName\'|\'eventCategory\'|false' => 'eventName',
    'secondaryDimension:"eventName"|"eventCategory"|false' => 'eventName',
    'secondaryDimension:\'eventAction\'|\'eventCategory\'|false' => 'eventAction',
    'secondaryDimension:"eventAction"|"eventCategory"|false' => 'eventAction',
    'featureName:string' => 'Example name',
    'like:bool|null' => true,
    'choice:string|null' => 'example_choice',
    'message:string|null' => 'example_message',
    'question:string' => 'example_question',
    'message:string|false' => 'example_message',
    'matchFormRules:array<int,array{attribute:string,pattern:string,value:string}>|false' => [
        'example',
    ],
    'matchPageRules:array<int,array{attribute:string,pattern:string,value:string}>|false' => [
        'example',
    ],
    'conversionRuleOption:string' => 'example_conversionRuleOption',
    'conversionRules:array<int,array{attribute:string,pattern:string,value:string}>|false' => [
        'example',
    ],
    'idGoal:int|null' => 1,
    'idForm:int' => 1,
    'idForm:int|false' => 1,
    'columns:string|array<int,string>|false' => [
        'example',
    ],
    'fields:array<int,array{name?:string,displayName?:string}>' => [
        'example',
    ],
    'idFunnel:int|false' => 1,
    'stepPosition:int' => 10,
    'idFunnel:int' => 1,
    'step:string|false' => 'example_step',
    'idGoal:int|string' => 1,
    'isActivated:bool|int|string' => true,
    'steps:array<int,array<string,mixed>>' => [
        'example',
    ],
    'funnelName:string' => 'Example name',
    'description:?string' => 'Example description',
    'url:string' => 'https://example.com/',
    'idGoal:int' => 1,
    'orderByName:bool' => true,
    'matchAttribute:string' => 'example_matchAttribute',
    'pattern:string' => 'example_pattern',
    'patternType:string' => 'example_patternType',
    'caseSensitive:bool' => true,
    'revenue:bool|float' => true,
    'allowMultipleConversionsPerVisit:bool' => true,
    'useEventValueAsRevenue:bool' => true,
    'abandonedCarts:bool' => true,
    'columns:string|string[]' => [
        'example',
    ],
    'showAllGoalSpecificMetrics:bool' => true,
    'compare:bool' => true,
    'matchPageRules:array' => [
        'example',
    ],
    'sampleLimit:int' => 100,
    'sampleRate:float' => 1.5,
    'excludedElements:string|false' => 'example_excludedElements',
    'screenshotUrl:string|false' => 'https://example.com/',
    'breakpointMobile:int|false' => 10,
    'breakpointTablet:int|false' => 10,
    'captureDomManually:bool' => true,
    'idSiteHsr:int' => 1,
    'minSessionTime:int' => 10,
    'requiresActivity:bool' => true,
    'captureKeystrokes:bool' => true,
    'includePageTreeMirror:bool|int' => true,
    'idLogHsr:int' => 1,
    'idVisit:int' => 1,
    'heatmapType:int' => 10,
    'deviceType:int' => 10,
    'graphType:\'evolution\'|\'verticalBar\'|\'horizontalBar\'|\'pie\'|\'3dPie\'|false' => 'evolution',
    'graphType:"evolution"|"verticalBar"|"horizontalBar"|"pie"|"3dPie"|false' => 'evolution',
    'outputType:int' => 10,
    'labels:string|false' => 'example_labels',
    'showLegend:bool' => true,
    'width:int|false' => 10,
    'height:int|false' => 10,
    'fontSize:int' => 10,
    'legendFontSize:int|false' => 10,
    'aliasedGraph:bool' => true,
    'colors:string|false' => 'example_colors',
    'textColor:string' => 'example_textColor',
    'backgroundColor:string' => 'example_backgroundColor',
    'gridColor:string' => 'example_gridColor',
    'legendAppendMetric:bool' => true,
    'comparedToXPeriods:int' => 10,
    'limitIncreaser:int' => 100,
    'limitDecreaser:int' => 100,
    'filterBy:\'\'|\'movers\'|\'new\'|\'disappeared\'' => '|',
    'filterBy:""|"movers"|"new"|"disappeared"' => '|',
    'minImpactPercent:int' => 10,
    'minGrowthPercent:int' => 10,
    'orderBy:\'absolute\'|\'relative\'|\'importance\'' => 'absolute',
    'orderBy:"absolute"|"relative"|"importance"' => 'absolute',
    'nonce:string' => 'example_nonce',
    'languageCode:string' => 'example_languageCode',
    '_ignoreConfig:bool' => true,
    'excludeNonCorePlugins:bool' => true,
    'use12HourClock:bool' => true,
    'idSite:int|int[]' => [
        1,
        2,
    ],
    'showColumns:string|string[]' => [
        'example',
    ],
    'hideColumns:string|string[]' => [
        'example',
    ],
    'period:\'day\'|\'week\'|\'month\'|\'year\'|\'range\'|false' => 'day',
    'period:"day"|"week"|"month"|"year"|"range"|false' => 'day',
    'countVisitorsToFetch:int|false' => 10,
    'minTimestamp:int|false' => 10,
    'doNotFetchActions:bool' => true,
    'enhanced:bool' => true,
    'visitorId:string|false' => 'example_visitorId',
    'limitVisits:int|false' => 100,
    'licenseKey:string' => 'example_licenseKey',
    'columns:string|string[]|false' => 'example_columns',
    'idSubtable:bool|int' => true,
    'secondaryDimension:bool|string' => true,
    '_expandAll:bool' => true,
    'provider:string' => 'example_provider',
    'credentials:array<string,string|int|null>' => [
        'example',
    ],
    'phoneNumber:string' => 'example_phoneNumber',
    'verificationCode:string' => 'example_verificationCode',
    'delegatedManagement:bool' => true,
    'isEnabled:bool|int|string' => true,
    'idCampaignDimensionCombination:int|string' => 1,
    'segment:string|null' => 'countryCode==NZ',
    '_restrictSitesToLogin:string|null' => 'example__restrictSitesToLogin',
    'pattern:string|null' => 'example_pattern',
    'clientId:string' => 'example_clientId',
    'grantTypes:string[]' => [
        'example',
    ],
    'scope:string' => 'example_scope',
    'redirectUris:string|string[]' => [
        'example',
    ],
    'active:string' => 'example_active',
    'format:string' => 'example_format',
    'plugin:string' => 'example_plugin',
    'visits:array<int,VisitDescriptor>' => [
        'example',
    ],
    'idSites:int|string|int[]' => [
        1,
        2,
    ],
    'anonymizeIp:bool' => true,
    'anonymizeLocation:bool' => true,
    'anonymizeUserId:bool' => true,
    'unsetVisitColumns:string[]' => [
        'example',
    ],
    'unsetLinkVisitActionColumns:string[]' => [
        'example',
    ],
    'passwordConfirmation:string' => 'example_passwordConfirmation',
    'typeReferrer:bool|int|string' => true,
    'idSubtable:int|null' => 1,
    '_setReferrerTypeLabel:bool' => true,
    'secondaryDimension:\'entryPageTitle\'|\'entryPageUrl\'|null' => 'entryPageTitle',
    'secondaryDimension:"entryPageTitle"|"entryPageUrl"|null' => 'entryPageTitle',
    'sourceIdSites:array<int|string>' => [
        'example',
    ],
    'timezone:string' => 'example_timezone',
    'currency:string' => 'example_currency',
    'name:string|null' => 'Example name',
    'sourceIdSites:array<int|string>|null' => [
        'example',
    ],
    'timezone:string|null' => 'example_timezone',
    'currency:string|null' => 'example_currency',
    'period:\'day\'|\'week\'|\'month\'|\'never\'' => 'day',
    'period:"day"|"week"|"month"|"never"' => 'day',
    'hour:int' => 10,
    'reportFormat:string' => 'example_reportFormat',
    'reports:list<string>' => 'example_reports',
    'parameters:array<string,mixed>' => [
        'example',
    ],
    'idSegment:int|false' => 1,
    'evolutionPeriodFor:\'prev\'|\'each\'' => 'prev',
    'evolutionPeriodFor:"prev"|"each"' => 'prev',
    'evolutionPeriodN:int|null' => 10,
    'periodParam:\'day\'|\'week\'|\'month\'|\'year\'|null' => 'day',
    'periodParam:"day"|"week"|"month"|"year"|null' => 'day',
    'idReport:int' => 1,
    'idSite:int|false' => 1,
    'period:\'day\'|\'week\'|\'month\'|\'never\'|false' => 'day',
    'period:"day"|"week"|"month"|"never"|false' => 'day',
    'idReport:int|false' => 1,
    'ifSuperUserReturnOnlySuperUserReports:bool' => true,
    'outputType:int|false' => 10,
    'reportFormat:string|false' => 'example_reportFormat',
    'parameters:array<string,mixed>|false' => [
        'example',
    ],
    'period:\'day\'|\'week\'|\'month\'|\'year\'|false' => 'day',
    'period:"day"|"week"|"month"|"year"|false' => 'day',
    'force:bool' => true,
    'idSegment:int' => 1,
    'definition:string' => 'example_definition',
    'autoArchive:bool' => true,
    'enabledAllUsers:bool' => true,
    'piwikUrl:string' => 'https://example.com/',
    'mergeSubdomains:bool' => true,
    'groupPageTitlesByDomain:bool' => true,
    'mergeAliasUrls:bool' => true,
    'visitorCustomVariables:array<int,array{string,string}>' => [
        'example',
    ],
    'pageCustomVariables:array<int,array{string,string}>' => [
        'example',
    ],
    'customCampaignNameQueryParam:string' => 'Example name',
    'customCampaignKeywordParam:string' => 'example_customCampaignKeywordParam',
    'doNotTrack:bool' => true,
    'disableCookies:bool' => true,
    'trackNoScript:bool' => true,
    'crossDomain:bool' => true,
    'forceMatomoEndpoint:bool' => true,
    'excludedQueryParams:string|string[]' => [
        'example',
    ],
    'excludedReferrers:string|string[]' => [
        'example',
    ],
    'disableCampaignParameters:bool' => true,
    'actionName:string|false' => 'Example name',
    'idGoal:int|false' => 1,
    'revenue:int|float|false' => 1.5,
    'group:string' => 'example_group',
    'fetchAliasUrls:bool' => true,
    'pattern:string|false' => 'example_pattern',
    'limit:int|false' => 100,
    'sitesToExclude:int[]' => [
        'example',
    ],
    'permission:string' => 'example_permission',
    'limit:int|null' => 100,
    'siteTypesToExclude:string[]' => [
        'example',
    ],
    '_restrictSitesToLogin:string|false' => 'example__restrictSitesToLogin',
    'siteName:string' => 'Example name',
    'urls:string[]|string|null' => 'https://example.com/',
    'ecommerce:int|null' => 10,
    'siteSearch:int|null' => 10,
    'searchKeywordParameters:string|null' => 'example_searchKeywordParameters',
    'searchCategoryParameters:string|null' => 'example_searchCategoryParameters',
    'excludedIps:string|null' => 'example_excludedIps',
    'excludedQueryParameters:string|null' => 'example_excludedQueryParameters',
    'group:string|null' => 'example_group',
    'startDate:string|null' => '2026-05-01 00:00:00',
    'excludedUserAgents:string|null' => 'example_excludedUserAgents',
    'keepURLFragments:int|null' => 10,
    'type:string|null' => 'example_type',
    'settingValues:SettingValues|null' => 'example_settingValues',
    'excludeUnknownUrls:bool|null' => true,
    'excludedReferrers:string|null' => 'example_excludedReferrers',
    'passwordConfirmation:string|null' => 'example_passwordConfirmation',
    'urls:string[]|string' => 'https://example.com/',
    'ipRange:string' => 'example_ipRange',
    'excludedIps:string' => 'example_excludedIps',
    'searchKeywordParameters:string' => 'example_searchKeywordParameters',
    'searchCategoryParameters:string' => 'example_searchCategoryParameters',
    'excludedUserAgents:string' => 'example_excludedUserAgents',
    'excludedReferrers:string' => 'example_excludedReferrers',
    'enabled:bool' => true,
    'defaultCurrency:string' => 'example_defaultCurrency',
    'defaultTimezone:string' => 'example_defaultTimezone',
    'exclusionType:string' => 'example_exclusionType',
    'queryParamsToExclude:string|null' => 'example_queryParamsToExclude',
    'siteName:string|null' => 'Example name',
    'countryCode:string|null' => 'example_countryCode',
    'multipleTimezonesInCountry:bool|null' => true,
    'oldGroupName:string' => 'Example name',
    'newGroupName:string' => 'Example name',
    'idContext:string' => 'example_idContext',
    'idContainer:string' => 'example_idContainer',
    'environment:string' => 'example_environment',
    'jsFramework:string' => 'example_jsFramework',
    'idContainerVersion:int' => 1,
    'fireTriggerIds:int[]' => [
        'example',
    ],
    'blockTriggerIds:int[]' => [
        'example',
    ],
    'fireLimit:string' => 'example_fireLimit',
    'fireDelay:int' => 10,
    'priority:int' => 10,
    'endDate:string|null' => '2026-05-01 00:00:00',
    'description:string|null' => 'Example description',
    'status:string' => 'running',
    'idTag:int' => 1,
    'idTrigger:int' => 1,
    'conditions:array<int,array<string,mixed>>' => [
        'example',
    ],
    'idVariable:int' => 1,
    'defaultValue:bool|float|int|string|null' => true,
    'lookupTable:array<int,array<string,mixed>>' => [
        'example',
    ],
    'context:string' => 'example_context',
    'ignoreGtmDataLayer:int' => 10,
    'isTagFireLimitAllowedInPreviewMode:int' => 100,
    'activelySyncGtmDataLayer:int' => 10,
    'idContainerVersion:int|null' => 1,
    'exportedContainerVersion:string' => 'example_exportedContainerVersion',
    'backupName:string' => 'Example name',
    '_isDraftRestoreCall:bool' => true,
    'id:string' => 'example_id',
    'pageTitle:string' => 'example_pageTitle',
    'limitBeforeGrouping:int|string' => 100,
    'actionName:string' => 'Example name',
    'actionType:\'url\'|\'title\'' => 'url',
    'actionType:"url"|"title"' => 'url',
    'parts:string' => 'example_parts',
    'userLogin:string' => 'example_userLogin',
    'ip:string|false' => 'example_ip',
    'provider:string|false' => 'example_provider',
    'providerId:string' => 'example_providerId',
    'dataSource:string|false' => 'example_dataSource',
    'limitActionsPerStep:int' => 100,
    'exploreStep:int|false' => 10,
    'exploreUrl:string|false' => 'https://example.com/',
    'interactionPosition:string' => 'example_interactionPosition',
    'offsetActionsPerStep:int|false' => 0,
    'preferenceName:string' => 'Example name',
    'preferenceValue:mixed' => 'example_preferenceValue',
    'userLogin:string|null|false' => 'example_userLogin',
    'offset:int|null' => 0,
    'filter_search:string|null' => 'example_filter_search',
    'filter_access:string|null' => 'example_filter_access',
    'filter_status:string|null' => 'running',
    'userLogins:string' => 'example_userLogins',
    'access:string' => 'example_access',
    'userEmail:string' => 'user@example.com',
    'password:string' => 'example_password',
    'email:string' => 'user@example.com',
    '_isPasswordHashed:bool' => true,
    'initialIdSite:int|null' => 10,
    'expiryInDays:int|null' => 10,
    'hasSuperUserAccess:bool|int|string' => true,
    'password:string|false' => 'example_password',
    'email:string|false' => 'user@example.com',
    'passwordConfirmation:string|false' => 'example_passwordConfirmation',
    'access:string|list<string>' => 'example_access',
    'idSites:string|int|int[]' => [
        1,
        2,
    ],
    'capabilities:string|string[]' => [
        'example',
    ],
    'idSites:int|int[]|string' => 1,
    'expireDate:string|null' => '2026-05-01',
    'expireHours:int|string' => 10,
    'secureOnly:bool' => true,
    'expiryInDays:int' => 10,
    'columns:list<string>|string|null' => 'example_columns',
    'hideFutureHoursWhenToday:bool' => true,
];