<?php

return [
    'idSite:int|string|int[]' => 1,
    'period:\'day\'|\'week\'|\'month\'|\'year\'|\'range\'' => 'day',
    'period:"day"|"week"|"month"|"year"|"range"' => 'day',
    'date:string' => 'yesterday',
    'idSite:int|string' => 1,
    'apiModule:string' => 'VisitsSummary',
    'apiAction:string' => 'get',
    'period:string' => 'day',
    'urls:string[]' => [
        'https://example.org',
        'https://example.org/pricing',
    ],
    'pluginName:string' => 'Goals',
    'segmentName:string' => 'New Zealand visitors',
    'idSite:int' => 1,
    'idExperiment:int' => 1,
    'successMetric:string' => 'conversion_rate',
    'name:string' => 'Pricing page signup test',
    'hypothesis:string' => 'A shorter signup flow will improve conversions.',
    'description:string' => 'Compare the pricing page signup experience for New Zealand traffic.',
    'variations:array<int,array<string,mixed>>' => [
        [
            'name' => 'Original pricing page',
            'percentage' => 50,
        ],
        [
            'name' => 'Short signup form',
            'percentage' => 50,
        ],
    ],
    'includedTargets:array<int,array<string,mixed>>' => [
        [
            'attribute' => 'url',
            'type' => 'equals',
            'value' => 'https://example.org/pricing',
        ],
    ],
    'successMetrics:array<int,array<string,mixed>>' => [
        [
            'metric' => 'conversion_rate',
        ],
    ],
    'confidenceThreshold:int|float|string' => 95,
    'mdeRelative:int' => 10,
    'percentageParticipants:int' => 100,
    'statuses:string|array<int,string>' => [
        'running',
        'finished',
    ],
    'pageUrl:string' => 'https://example.org/pricing',
    'pageName:string' => 'Pricing',
    'downloadUrl:string' => 'https://example.org/files/brochure.pdf',
    'outlinkUrl:string' => 'https://partner.example.com/signup',
    'idExport:int' => 7,
    'type:string' => 'html',
    'parameters:string' => 'module=API&method=VisitsSummary.get&idSite=1&period=day&date=2026-05-01&format=html',
    'note:string' => 'Investigate conversion spike from NZ campaign traffic.',
    'idNote:int' => 12,
    'idSite:string' => '1',
    'idSubtable:int' => 2,
    'displayDateRange:string' => '2026-05-01,2026-05-07',
    'cohorts:string' => '2026-05-01,2026-05-07',
    'idFailure:int|string' => 3,
    'idLogCrashes:int[]|int|string' => [101, 102],
    'idLogCrash:int' => 101,
    'idAlert:int' => 1,
    'subPeriodN:int|string' => 1,
    'idSites:string|array' => [
        1,
        2,
    ],
    'period:\'day\'|\'week\'|\'month\'' => 'day',
    'period:"day"|"week"|"month"' => 'day',
    'emailMe:bool' => true,
    'additionalEmails:list<string>' => [
        'alice@example.org',
    ],
    'phoneNumbers:list<string>' => [
        '+64211234567',
    ],
    'metric:string' => 'nb_visits',
    'metricCondition:string' => 'nb_conversions',
    'metricValue:float|int|string' => 10,
    'comparedTo:int' => 1,
    'reportUniqueId:string' => 'VisitsSummary_get',
    'idDimension:int' => 1,
    'scope:\'visit\'|\'action\'' => 'action',
    'scope:"visit"|"action"' => 'action',
    'active:bool|int' => true,
    'idCustomReport:int' => 1,
    'reportType:string' => 'table',
    'metricIds:string[]' => [
        'nb_visits',
        'nb_conversions',
        'conversion_rate',
    ],
    'idSubtable:int|string|false' => 1,
    'login:string' => 'alice',
    'idDashboard:int' => 1,
    'copyToUser:string' => 'alice',
    'featureName:string' => 'FormAnalytics',
    'question:string' => 'Which pricing page sections get the most engagement?',
    'idForm:int' => 1,
    'lastMinutes:int' => 30,
    'stepPosition:int' => 1,
    'idFunnel:int' => 1,
    'idGoal:int|string' => 1,
    'isActivated:bool|int|string' => true,
    'funnelName:string' => 'Pricing Signup Funnel',
    'steps:array<int,array<string,mixed>>' => [
        [
            'name' => 'Pricing Page',
            'url' => 'https://example.org/pricing',
        ],
        [
            'name' => 'Signup Page',
            'url' => 'https://partner.example.com/signup',
        ],
    ],
    'url:string' => 'https://example.org/pricing',
    'idGoal:int' => 1,
    'matchAttribute:string' => 'url',
    'pattern:string' => 'https://example.org/pricing',
    'patternType:string' => 'equals',
    'matchPageRules:array' => [
        [
            'attribute' => 'url',
            'type' => 'equals',
            'value' => 'https://example.org/pricing',
        ],
    ],
    'idSiteHsr:int' => 1,
    'idLogHsr:int' => 101,
    'idVisit:int' => 1001,
    'heatmapType:int' => 1,
    'deviceType:int' => 1,
    'languageCode:string' => 'en',
    'use12HourClock:bool' => true,
    'idSite:int|int[]' => 1,
    'licenseKey:string' => 'hsr-demo-license',
    'provider:string' => 'google',
    'phoneNumber:string' => '+64211234567',
    'verificationCode:string' => '123456',
    'delegatedManagement:bool' => true,
    'isEnabled:bool|int|string' => true,
    'memberOf:string' => 'cn=matomo-users,ou=groups,dc=example,dc=org',
    'filter:string' => '(objectClass=person)',
    'initialIdSite:int' => 1,
    'clientId:string' => '0123456789abcdef0123456789abcdef',
    'grantTypes:string[]' => ['authorization_code'],
    'scope:string' => 'matomo:read',
    'active:string' => '1',
    'plugin:string' => 'HeatmapSessionRecording',
    'format:string' => 'html',
    'visits:array<int,VisitDescriptor>' => [
        [
            'idvisit' => 12345,
            'idsite' => 1,
        ],
    ],
    'segment:string' => 'countryCode==NZ',
    'idSites:int|string|int[]' => [
        1,
        2,
    ],
    'sourceIdSites:array<int|string>' => [
        1,
        2,
    ],
    'sourceIdSites:integer|(integer|array<string>)' => [
        1,
        2,
    ],
    'sourceIdSites:integer | (integer | array<string>)' => [
        1,
        2,
    ],
    'timezone:string' => 'Pacific/Auckland',
    'currency:string' => 'NZD',
    'period:\'day\'|\'week\'|\'month\'|\'never\'' => 'never',
    'period:"day"|"week"|"month"|"never"' => 'never',
    'hour:int' => 9,
    'reportFormat:string' => 'pdf',
    'reports:list<string>' => [
        'VisitsSummary.get',
        'Goals.get',
    ],
    'parameters:array<string,mixed>' => [
        'module' => 'VisitsSummary',
        'action' => 'get',
    ],
    'idReport:int' => 1,
    'idSite:int|null' => 1,
    'idSegment:int' => 1,
    'definition:string' => 'countryCode==NZ',
    'permission:string' => 'view',
    'siteName:string' => 'Example NZ Site',
    'urls:string[]|string' => [
        'https://example.org',
        'https://example.org/pricing',
    ],
    'ipRange:string' => '203.0.113.0/24',
    'excludedIps:string' => '203.0.113.10,203.0.113.11',
    'searchKeywordParameters:string' => 'q,query,keyword',
    'searchCategoryParameters:string' => 'category,cat',
    'excludedUserAgents:string' => 'HeadlessChrome,Googlebot',
    'excludedReferrers:string' => 'partner.example.com,internal.example.org',
    'enabled:bool' => true,
    'defaultCurrency:string' => 'NZD',
    'defaultTimezone:string' => 'Pacific/Auckland',
    'exclusionType:string' => 'ip',
    'oldGroupName:string' => 'Marketing Team',
    'newGroupName:string' => 'Growth Team',
    'idContext:string' => 'web',
    'idContainer:string' => 'GTMNZ123',
    'environment:string' => 'live',
    'idContainerVersion:int' => 3,
    'idTag:int' => 2,
    'idTrigger:int' => 3,
    'idVariable:int' => 4,
    'context:string' => 'web',
    'exportedContainerVersion:string' => 'live-v3',
    'id:string' => 'pricing-signup-goal',
    'pageTitle:string' => 'Pricing',
    'actionName:string' => 'Pricing Page',
    'actionType:\'url\'|\'title\'' => 'url',
    'actionType:"url"|"title"' => 'url',
    'userLogin:string' => 'alice',
    'providerId:string' => 'google',
    'interactionPosition:string' => 'header',
    'preferenceName:string' => 'reportFormat',
    'preferenceValue:mixed' => 'pdf',
    'access:string' => 'view',
    'userEmail:string' => 'alice@example.org',
    'password:string' => 'correct-horse-battery-staple',
    'email:string' => 'alice@example.org',
    'hasSuperUserAccess:bool|int|string' => true,
    'access:string|list<string>' => ['view'],
    'idSites:string|int|int[]' => [1, 2],
    'capabilities:string|string[]' => ['read:reports'],
    'idSites:int|int[]|string' => [1, 2],
    'passwordConfirmation:string' => 'correct-horse-battery-staple',
];
